name: Node CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ubuntu Version
        run: cat /etc/os-release

      - name: Docker Version
        run: docker version

      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node_modules
        with:
          path: node_modules
          key: utils-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            utils-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
            utils-${{ env.cache-name }}-
            utils-

      - run: docker-compose build
      - run: docker-compose run --rm app yarn install
      - run: docker-compose run --rm app yarn run build
      - run: docker-compose run --rm app yarn run lint

      - name: Slack Notification
        uses: homoluctus/slatify@v1.6
        if: failure()
        with:
          job_name: '*${{ github.workflow }}*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
