name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.1]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node_modules
        with:
          path: node_modules
          key: utils-net-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            utils-net-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
            utils-net-build-${{ env.cache-name }}-
            utils-net-build-
            utils-net-

      - name: Run yarn install
        run: yarn install

      - name: Run yarn build
        run: yarn run build

      - name: Run yarn lint
        run: yarn run lint

      - name: Slack Notification
        uses: homoluctus/slatify@v1.6
        if: failure()
        with:
          job_name: '*Node CI*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
